return {
  ['1'] = { key = '1', alt = false, shift = false },
  ['2'] = { key = '2', alt = false, shift = false },
  ['3'] = { key = '3', alt = false, shift = false },
  ['4'] = { key = '4', alt = false, shift = false },
  ['5'] = { key = '5', alt = false, shift = false },
  ['6'] = { key = '6', alt = false, shift = false },
  ['7'] = { key = '7', alt = false, shift = false },
  ['8'] = { key = '8', alt = false, shift = false },
  ['9'] = { key = '9', alt = false, shift = false },
  ['0'] = { key = '0', alt = false, shift = false },

  ['q'] = { key = 'q', alt = false, shift = false },
  ['w'] = { key = 'g', alt = false, shift = false },
  ['e'] = { key = 'm', alt = false, shift = false },
  ['r'] = { key = 'l', alt = false, shift = false },
  ['t'] = { key = 'w', alt = false, shift = false },
  ['y'] = { key = 'y', alt = false, shift = false },
  ['u'] = { key = 'f', alt = false, shift = false },
  ['i'] = { key = 'u', alt = false, shift = false },
  ['o'] = { key = 'b', alt = false, shift = false },
  ['p'] = { key = '-', alt = false, shift = false },

  ['a'] = { key = 'd', alt = false, shift = false },
  ['s'] = { key = 's', alt = false, shift = false },
  ['d'] = { key = 't', alt = false, shift = false },
  ['f'] = { key = 'n', alt = false, shift = false },
  ['g'] = { key = 'r', alt = false, shift = false },
  ['h'] = { key = 'i', alt = false, shift = false },
  ['j'] = { key = 'a', alt = false, shift = false },
  ['k'] = { key = 'e', alt = false, shift = false },
  ['l'] = { key = 'o', alt = false, shift = false },
  [';'] = { key = 'h', alt = false, shift = false },

  ['z'] = { key = 'z', alt = false, shift = false },
  ['x'] = { key = 'x', alt = false, shift = false },
  ['c'] = { key = 'c', alt = false, shift = false },
  ['v'] = { key = 'v', alt = false, shift = false },
  ['b'] = { key = 'j', alt = false, shift = false },
  ['n'] = { key = 'k', alt = false, shift = false },
  ['m'] = { key = 'p', alt = false, shift = false },
  [','] = { key = ',', alt = false, shift = false },
  ['.'] = { key = '.', alt = false, shift = false },
  ['/'] = { key = '/', alt = false, shift = false }
}
