return {
  ['1'] = { key = 'none', alt = false, shift = false },
  ['2'] = { key = 'none', alt = false, shift = false },
  ['3'] = { key = 'none', alt = false, shift = false },
  ['4'] = { key = 'none', alt = false, shift = false },
  ['5'] = { key = 'none', alt = false, shift = false },
  ['6'] = { key = '3',    alt = false, shift = true  },
  ['7'] = { key = 'tab',  alt = false, shift = false },
  ['8'] = { key = 'pad/', alt = false, shift = false },
  ['9'] = { key = 'pad*', alt = false, shift = false },
  ['0'] = { key = 'pad-', alt = false, shift = false },

  ['q'] = { key = 'pageup',        alt = false, shift = false },
  ['w'] = { key = 'delete',        alt = false, shift = false },
  ['e'] = { key = 'up',            alt = false, shift = false },
  ['r'] = { key = 'forwarddelete', alt = false, shift = false },
  ['t'] = { key = 'pagedown',      alt = false, shift = false },
  ['y'] = { key = 'none',          alt = false, shift = false },
  ['u'] = { key = 'pad7',          alt = false, shift = false },
  ['i'] = { key = 'pad8',          alt = false, shift = false },
  ['o'] = { key = 'pad9',          alt = false, shift = false },
  ['p'] = { key = 'pad+',          alt = false, shift = false },

  ['a'] = { key = 'home',  alt = false, shift = false },
  ['s'] = { key = 'left',  alt = false, shift = false },
  ['d'] = { key = 'down',  alt = false, shift = false },
  ['f'] = { key = 'right', alt = false, shift = false },
  ['g'] = { key = 'end',   alt = false, shift = false },
  ['h'] = { key = ',',     alt = false, shift = false },
  ['j'] = { key = 'pad4',  alt = false, shift = false },
  ['k'] = { key = 'pad5',  alt = false, shift = false },
  ['l'] = { key = 'pad6',  alt = false, shift = false },
  [';'] = { key = ';',     alt = false, shift = true  },

  ['z'] = { key = 'escape',   alt = false, shift = false },
  ['x'] = { key = 'tab',      alt = false, shift = false },
  ['c'] = { key = 'none',     alt = false, shift = false }, -- TODO: insert.
  ['v'] = { key = 'padenter', alt = false, shift = false },
  ['b'] = { key = 'none',     alt = false, shift = false }, -- TODO: undo.
  ['n'] = { key = 'pad.',     alt = false, shift = false },
  ['m'] = { key = 'pad1',     alt = false, shift = false },
  [','] = { key = 'pad2',     alt = false, shift = false },
  ['.'] = { key = 'pad3',     alt = false, shift = false },
  ['/'] = { key = ';',        alt = false, shift = false }
}
