return {
  ['1'] = { key = '1', alt = false, shift = false },
  ['2'] = { key = '2', alt = false, shift = false },
  ['3'] = { key = '3', alt = false, shift = false },
  ['4'] = { key = '4', alt = false, shift = false },
  ['5'] = { key = '5', alt = false, shift = false },
  ['6'] = { key = '6', alt = false, shift = false },
  ['7'] = { key = '7', alt = false, shift = false },
  ['8'] = { key = '8', alt = false, shift = false },
  ['9'] = { key = '9', alt = false, shift = false },
  ['0'] = { key = '0', alt = false, shift = false },

  ['q'] = { key = '§', alt = false, shift = false },
  ['w'] = { key = '-', alt = false, shift = true  },
  ['e'] = { key = '[', alt = false, shift = false },
  ['r'] = { key = ']', alt = false, shift = false },
  ['t'] = { key = '6', alt = false, shift = true  },
  ['y'] = { key = '1', alt = false, shift = true  },
  ['u'] = { key = ',', alt = false, shift = true  },
  ['i'] = { key = '.', alt = false, shift = true  },
  ['o'] = { key = '=', alt = false, shift = false },
  ['p'] = { key = '3', alt = false, shift = true  },

  ['a'] = { key = '\\', alt = false, shift = false },
  ['s'] = { key = '/',  alt = false, shift = false },
  ['d'] = { key = '[',  alt = false, shift = true  },
  ['f'] = { key = ']',  alt = false, shift = true  },
  ['g'] = { key = '8',  alt = false, shift = true  },
  ['h'] = { key = '/',  alt = false, shift = true  },
  ['j'] = { key = '9',  alt = false, shift = true  },
  ['k'] = { key = '0',  alt = false, shift = true  },
  ['l'] = { key = '-',  alt = false, shift = false },
  [';'] = { key = ';',  alt = false, shift = true  },

  ['z'] = { key = '3',  alt = true,  shift = false },
  ['x'] = { key = '4',  alt = false, shift = true  },
  ['c'] = { key = '\\', alt = false, shift = true  },
  ['v'] = { key = '`',  alt = false, shift = true  },
  ['b'] = { key = '`',  alt = false, shift = false },
  ['n'] = { key = '=',  alt = false, shift = true  },
  ['m'] = { key = '5',  alt = false, shift = true  },
  [','] = { key = '2',  alt = false, shift = true  },
  ['.'] = { key = '7',  alt = false, shift = true  },
  ['/'] = { key = ';',  alt = false, shift = false }
}
